from datetime import datetime, timezone
from models.schema import (
    TriageRequest,
    TriageResponse,
    EvidenceChunk,
    UrgencyTier,
    ConfidenceLevel,
)
from services.supabase_service import supabase


def calculate_temporary_triage(request: TriageRequest) -> dict:
    """
    Temporary rule-based triage logic.

    This is only for the first working backend version.
    Later, we will replace this with:
    RAG retrieval + Groq LLM decision.
    """

    chief_complaint = request.chief_complaint.lower()
    symptom_text = " ".join([item.symptom.lower() for item in request.symptoms])

    combined_text = f"{chief_complaint} {symptom_text}"

    has_severe_symptom = any(
        item.severity == "severe"
        for item in request.symptoms
    )

    has_sudden_onset = any(
        item.onset == "sudden"
        for item in request.symptoms
    )

    oxygen_saturation = None
    heart_rate = None
    temperature_f = None

    if request.vitals:
        oxygen_saturation = request.vitals.oxygen_saturation
        heart_rate = request.vitals.heart_rate
        temperature_f = request.vitals.temperature_f

    emergency_keywords = [
        "chest pain",
        "stroke",
        "weakness on one side",
        "face drooping",
        "trouble speaking",
        "shortness of breath",
        "severe bleeding",
        "loss of consciousness",
        "seizure",
    ]

    urgent_keywords = [
        "fever",
        "abdominal pain",
        "vomiting",
        "dehydration",
        "infection",
        "wheezing",
        "dizziness",
    ]

    has_emergency_keyword = any(
        keyword in combined_text
        for keyword in emergency_keywords
    )

    has_urgent_keyword = any(
        keyword in combined_text
        for keyword in urgent_keywords
    )

    if (
        has_emergency_keyword
        or oxygen_saturation is not None and oxygen_saturation < 90
        or has_severe_symptom and has_sudden_onset
    ):
        return {
            "urgency_tier": UrgencyTier.EMERGENCY,
            "urgency_score": 90,
            "confidence_level": ConfidenceLevel.MEDIUM,
            "ai_reasoning": (
                "The presentation includes possible emergency red flags such as "
                "severe symptoms, sudden onset, chest pain, neurologic symptoms, "
                "or low oxygen saturation. This should be treated as potentially "
                "life-threatening until reviewed by a clinician."
            ),
            "recommended_action": (
                "Activate emergency protocol or arrange immediate emergency evaluation."
            ),
        }

    if (
        has_urgent_keyword
        or heart_rate is not None and heart_rate > 120
        or temperature_f is not None and temperature_f >= 101
        or has_severe_symptom
    ):
        return {
            "urgency_tier": UrgencyTier.URGENT,
            "urgency_score": 65,
            "confidence_level": ConfidenceLevel.MEDIUM,
            "ai_reasoning": (
                "The presentation includes symptoms or vital signs that may require "
                "same-day medical evaluation, but no immediate life-threatening "
                "red flag was clearly identified."
            ),
            "recommended_action": (
                "Schedule same-day clinician or specialist review."
            ),
        }

    return {
        "urgency_tier": UrgencyTier.ROUTINE,
        "urgency_score": 25,
        "confidence_level": ConfidenceLevel.HIGH,
        "ai_reasoning": (
            "The reported symptoms appear mild and do not currently show obvious "
            "emergency or same-day urgent red flags based on the available intake data."
        ),
        "recommended_action": (
            "Schedule routine follow-up within 1 to 7 days, with instructions to seek "
            "urgent care if symptoms worsen."
        ),
    }


async def run_temporary_triage_pipeline(request: TriageRequest) -> TriageResponse:
    """
    First real triage pipeline:
    1. Validate request through Pydantic
    2. Calculate temporary triage result
    3. Save case to Supabase
    4. Write audit log
    5. Return structured triage response
    """

    triage_result = calculate_temporary_triage(request)

    evidence_list = [
        {
            "source": "Temporary Rule-Based Triage",
            "content": (
                "This result was generated by temporary backend rules. "
                "RAG and Groq LLM evidence will be added in the next AI phase."
            ),
            "relevance_score": 1.0,
        }
    ]

    case_data = {
        "patient_name": request.patient_name,
        "patient_age": request.patient_age,
        "patient_gender": request.patient_gender,
        "chief_complaint": request.chief_complaint,
        "symptoms": [
            symptom.model_dump()
            for symptom in request.symptoms
        ],
        "vitals": request.vitals.model_dump() if request.vitals else None,
        "medical_history": request.medical_history,
        "current_medications": request.current_medications,
        "allergies": request.allergies,
        "urgency_tier": triage_result["urgency_tier"].value,
        "urgency_score": triage_result["urgency_score"],
        "confidence_level": triage_result["confidence_level"].value,
        "ai_reasoning": triage_result["ai_reasoning"],
        "recommended_action": triage_result["recommended_action"],
        "retrieved_evidence": evidence_list,
        "status": "PENDING",
    }

    case_result = (
        supabase
        .table("records")
        .insert(case_data)
        .execute()
    )

    if not case_result.data:
        raise RuntimeError("Failed to insert case into Supabase.")

    case_id = case_result.data[0]["id"]

    audit_data = {
        "case_id": case_id,
        "action": "AI_TRIAGE",
        "details": {
            "pipeline_stage": "temporary_rule_based_triage",
            "triage_result": {
                "urgency_tier": triage_result["urgency_tier"].value,
                "urgency_score": triage_result["urgency_score"],
                "confidence_level": triage_result["confidence_level"].value,
                "ai_reasoning": triage_result["ai_reasoning"],
                "recommended_action": triage_result["recommended_action"],
            },
            "timestamp": datetime.now(timezone.utc).isoformat(),
        },
    }

    supabase.table("audit_log").insert(audit_data).execute()

    return TriageResponse(
        case_id=case_id,
        urgency_tier=triage_result["urgency_tier"],
        urgency_score=triage_result["urgency_score"],
        confidence_level=triage_result["confidence_level"],
        ai_reasoning=triage_result["ai_reasoning"],
        recommended_action=triage_result["recommended_action"],
        retrieved_evidence=[
            EvidenceChunk(**item)
            for item in evidence_list
        ],
    )